version: '2.22'

services:
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        volumes:
            - esdata01:/usr/share/elasticsearch/data
        ports:
            - ${ES_PORT}:9200
        environment:
            - discovery.type=single-node
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
        mem_limit: ${MEM_LIMIT}
        ulimits:
            memlock:
                soft: -1
                hard: -1
        healthcheck:
            test: ['CMD-SHELL', 'curl -s -I http://localhost:9200']
            interval: 10s
            timeout: 10s
            retries: 120

    kibana:
        depends_on:
            es01:
                condition: service_healthy
        image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
        volumes:
            - kibanadata:/usr/share/kibana/data
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        ports:
            - ${KIBANA_PORT}:5601
        environment:
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
        mem_limit: ${MEM_LIMIT}
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
                ]
            interval: 10s
            timeout: 10s
            retries: 120

volumes:
    esdata01:
        driver: local
    kibanadata:
        driver: local
